
// action常量
export const OPPORTUNITY = {
  RECEIVE_OPPORTUNITY_LIST: 'RECEIVE_APPROVAL_LIST',
  RECEIVE_FETCHING: 'RECEIVE_FETCHING',
  RECEIVE_REQUST_OPPORTUNITY: 'RECEIVE_REQUST_OPPORTUNITY',
  RECEIVE_OPPORTUNITY_STATUS_SUBMIT: 'RECEIVE_OPPORTUNITY_STATUS_SUBMIT',
  RECEIVE_OPPORTUNITY_HISTORY_LIST: 'RECEIVE_OPPORTUNITY_HISTORY_LIST',
  RECEIVE_OPPORTUNITY_HISTORY_SUBMIT: 'RECEIVE_OPPORTUNITY_HISTORY_SUBMIT',
  RECEIVE_OPPORTUNITY_SUBMIT: 'RECEIVE_APPROVAL_SUBMIT',
  RECEIVE_GET_OPPORTUNITY_NUM: 'RECEIVE_GET_OPPORTUNITY_NUM',
  RECEIVE_MAKE_CALL: 'RECEIVE_MAKE_CALL',
  RECEIVE_OPPORTUNITY_SOURCE: 'RECEIVE_OPPORTUNITY_SOURCE',
  RECEIVE_OPPORTUNITY_UNHOLD_REASON: 'RECEIVE_OPPORTUNITY_UNHOLD_REASON',
  RECEIVE_TRACKING_HISTORY_TYPE: 'RECEIVE_TRACKING_HISTORY_TYPE'
};

// EVENT_TYPES
export const EVENT_TYPES = {
  SHOW_NEW_OPPORTUNITY_MODAL: 'SHOW_NEW_OPPORTUNITY_MODAL',
  HIDE_NEW_OPPORTUNITY_MODAL: 'HIDE_NEW_OPPORTUNITY_MODAL'
};